###################################
# F I T Z  N E T  H A R D C O R E #
###################################

# MAXIMUM amount of lives a player can have before ban/kick/adventure mode
MaxLives: 3

# How long should it take to regenerate a life?
LifeRegenTime: 8

# How many lives should each player start with?
StartingLives: 1