###################################
# F I T Z  N E T  H A R D C O R E #
###################################

# MAXIMUM amount of lives a player can have before ban/kick/adventure mode
MaxLives: 3

# How long should it take to regenerate a life?
# IN MINUITES || Ex) 2 * 1200ms -- 2 Min Timer
LifeRegenTime: 2

# How many lives should each player start with?
StartingLives: 1

# Default action on last life
# 1 - Kick & Ban from server
# 2 - Spectate world on Death

LastLifeMode: 1
