name: Fitz-NetHardcore
version: 1.15.2-SNAPSHOT
main: org.fitznet.doomdns.fitznethardcore.FitzNetHardcore
api-version: 1.15
authors: [MatthewFitzgerald]
description: Hardcore mod. Gives lives and regen.
website: fitznet.doomdns.org
commands:
  lives:
    description: Display how many lives you have left.
    usage: /<command>
  addlife:
    description: Add one life.
    usage: /addlife
  removelife:
    description: Remove one life.
    usage: /<command>